version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      container_name: "gitlab"
      restart: unless-stopped
      privileged: true
      hostname: 'gitlab'
#      environment:
#        TZ: 'Asia/Shanghai'
#        GITLAB_OMNIBUS_CONFIG: |
#          external_url 'http://129.204.133.242'
#          gitlab_rails['time_zone'] = 'Asia/Shanghai'
#          gitlab_rails['smtp_enable'] = true
#          gitlab_rails['smtp_address'] = "smtp.aliyun.com"
#          gitlab_rails['smtp_port'] = 465
#          gitlab_rails['smtp_user_name'] = "kimasd102419@aliyun.com"  #用自己的aliyun邮箱
#          gitlab_rails['smtp_password'] = "axbc1kof"
#          gitlab_rails['smtp_domain'] = "aliyun.com"
#          gitlab_rails['smtp_authentication'] = "login"
#          gitlab_rails['smtp_enable_starttls_auto'] = true
#          gitlab_rails['smtp_tls'] = true
#          gitlab_rails['gitlab_email_from'] = 'kimasd102419@aliyun.com'
#          gitlab_rails['gitlab_shell_ssh_port'] = 22
      ports:
        - '81:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - $HOME/_data/gitlab/gitlab-data/config:/etc/gitlab
        - $HOME/_data/gitlab/gitlab-data/logs:/var/log/gitlab
        - $HOME/_data/gitlab/gitlab-data/data:/var/opt/gitlab
        - /etc/localtime:/etc/localtime
