version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      container_name: "gitlab"
      restart: unless-stopped
      privileged: true
      hostname: 'gitlab'
      ports:
        - '81:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - $HOME/_data/gitlab/gitlab-data/config:/etc/gitlab
        - $HOME/_data/gitlab/gitlab-data/logs:/var/log/gitlab
        - $HOME/_data/gitlab/gitlab-data/data:/var/opt/gitlab
        - /etc/localtime:/etc/localtime
